### ISSUE TITLE
Any min version requirement?

### ISSUE THREAD

**Issue by scrapmac** [axaluss/power-mode-intellij-plugin#1]
Hi, I am trying to install this plugin from disk and when I load the zip file, it says that the plugin is not compatible with my IntelliJ 14.1.4. I am installing manually from disk as I cannot find this plugin in the plugin store. Is there a min version of IntelliJ restriction?

**Comment by axaluss** [comment]
You can change the minimum build version here: https://github.com/axaluss/power-mode-intellij-plugin/blob/master/resources/META-INF/plugin.xml 
Build 143 is minimum Version. You can unzip the release and change that number in Plugin.xml to your build number and ZIP it back and try if it works. Please report back if it works such that i can change the build number.

**Comment by scrapmac** [comment]
doesn't work with build 141. Exception around NoSuchMethodError for com.intellij.openapi.editor.actionSystem.TypedAction.getRawHandler

**Comment by scrapmac** [comment]
I updated my IntelliJ and it works now.
