### ISSUE TITLE
Building Plugin

### ISSUE THREAD

**Issue by Victory** [axaluss/power-mode-intellij-plugin#13]
Hello and thank you for this fun plugin,

I am working to change the bam.png image to a custom image. 

To do this I have forked the repo and imported it to inteillij Ultimate Edition. However I am not very familiar with Scala and am having issues building the project. I have added the Scala sdk. I can see that there are CDI configurations, however I don't get a default run configuration in Intellij. I am use to having options in gradle, maven or ant to build the jar file. I was hoping that you could help me build this project into a jar file that I can import to intellij so I can run the plugin.

Can you tell me how i might go about that? It might also be helpful to update the README.md to explain how to configure and extend the plugin.

Thanks much
    ~ Victory

**Comment by pavankataria** [comment]
Yeah for sure man. This is something I'm looking to do! 

Or, if it may make things easier, could you add an input field for the image bam, so that we can edit it as we like? That would really be awesome. Thank you for your work.

**Comment by axaluss** [comment]
Take a look at the latest readme.md.
@Victory when you don't want to add the picture option @pavankataria proposed please consider to create another ticket.

Have fun learning scala ;)

**Comment by axaluss** [comment]
created issue "customizable BAM! image" #16

**Comment by pavankataria** [comment]
What's going on? lol Confused :P
