### ISSUE TITLE
Release 2.12.4 does not work with Pycharm 2016.1

### ISSUE THREAD

**Issue by thorntonjohn** [axaluss/power-mode-intellij-plugin#18]
I upgrade and then was unable to type. There were errors in the event log (sorry did not save them). I reverted back and the problem was fixed. Let me know if you want me to upgrade again and get the logs. Not sure if you are supporting backward compatibility.

**Comment by axaluss** [comment]
An error log would be helpful.

Am 27.02.2017 23:54 schrieb "John Thornton" <notifications@github.com>:

**Comment by axaluss** [comment]
fixed in 2.12.6
