### ISSUE TITLE
Disabling "Shake" does not work

### ISSUE THREAD

**Issue by gpaton** [axaluss/power-mode-intellij-plugin#2]
I try to disable *shake* option by unchecking the box **SHAKE!** or/and by reducing **shake range** to `0` but it has no effect and the window is still shaking.

Environment :
- Mac OS X 10.11.5 (El Capitan)
- PHPStorm 2016.1.2

**Comment by axaluss** [comment]
I can't reproduce this problem on my linux machine. 
Could you provide some intellij log files?

**Comment by gpaton** [comment]
> Also you should not install "Power mode II"(this one) and "power mode"(the other one) side by side.

Ok! I had the two plugins installed side by side. I removed the other one and it works now. Thanks for your help.
