### ISSUE TITLE
Power Indicator stuck at 100%

### ISSUE THREAD

**Issue by robtaireeo** [axaluss/power-mode-intellij-plugin#22]
Hi,

After the last update with power indicator, it just sits at 100%. Is this expected?

Also, the hover label is the same one from the BAM feature.

**Comment by axaluss** [comment]
Hi,
would you please provide a screenshot of your power mode settings or the powermode.xml file?
Which version are you using?

**Comment by axaluss** [comment]
Btw if you put "heatup base level" to 100% the heatup will stay at 100%. Reduce the base level to get the indicator unstuck.

**Comment by robtaireeo** [comment]
Ahh, it was that setting. it now works. thanks
