### ISSUE TITLE
Some ideas for improvement

### ISSUE THREAD

**Issue by sakhdevel** [axaluss/power-mode-intellij-plugin#23]
1. Sparks are cool. But here is another crazy idea.
Something like minigun shooting at the caret during typing and when user press space there is a shotgun (or bazooka) shoot and meat scattering in different directions :gun:
Meat could be something like these or may be something like quake meat 
![image](https://cloud.githubusercontent.com/assets/23290296/25226499/ece01d50-2610-11e7-8c86-1582073665f8.png)
or may be some wizard is casting his magic which creates new symbols that you type in.
2. Option: If a user is typing rather fast without errors (without pressing backspace) so then there should be more effects or they should be increased. If effects are cool it will stimulate avoiding errors :+1: 
3. May be there should be some effects when user fix warnings, it may stimulate him as well
P.S: thanks for very nice plugin!

**Comment by axaluss** [comment]
try release [3.14.159](https://github.com/axaluss/power-mode-intellij-plugin/tree/3.14.159)

**Comment by simplylouis** [comment]
great project!
Feature request: can i be able to customise my bam! image size please?
Also it seems a little bit laggy in mac OS . Thanks:D

**Comment by axaluss** [comment]
@simplylouis already played around with the PowerMode Settings? 
Like modifying the "frames per second" oder reducing the amount of particles?
The settings greatly influence the performance behavior.
The BAM! image size tries to reflect the amount of code change.
[Few changes=small image, many changes = large image.](https://github.com/axaluss/power-mode-intellij-plugin/blob/master/src/de/ax/powermode/power/management/ElementOfPowerContainer.scala#L85)
Feel free to add settings for bam image size and create a pull request :)

**Comment by axaluss** [comment]
- The latest version of power mode II allows custom BAM! and FLAME images.
- There is a power indicator showing how fabulous you are coding.
- The heatup feature shows more action the faster you code.
