### ISSUE TITLE
Power Mode II using excess CPU

### ISSUE THREAD

**Issue by dmills-yesware** [axaluss/power-mode-intellij-plugin#25]
Even when my JetBrains editor (RubyMine, in my case) is idle in the background, Power Mode II is using ~33% of my available CPU.

![image](https://cloud.githubusercontent.com/assets/8228622/26206770/af07ba66-3bb3-11e7-9f8d-4c8d85eda884.png)
![image](https://cloud.githubusercontent.com/assets/8228622/26206773/b2a04954-3bb3-11e7-8a98-856884ccc51f.png)

As you can see above, profiling RubyMine's execution using JVisualVM shows that Power Mode II accounts for nearly all of its idle processing.

Thanks for the great plugin! I *love* Power Mode II 😄

**Comment by axaluss** [comment]
how high did you set the framerate?
If you want lower cpu usage reduce the framerate.

**Comment by dmills-yesware** [comment]
Thanks for the quick reply! 

The sample I pasted above was with the framerate set at the default of 30fps. Lowering it to the minimum of 5fps does indeed reduce RubyMine's idle CPU consumption from ~30% to ~10%. 

![image](https://cloud.githubusercontent.com/assets/8228622/26222975/0f185c0e-3bea-11e7-802a-479a0495faa1.png)
![image](https://cloud.githubusercontent.com/assets/8228622/26222970/0a2f6f2a-3bea-11e7-8eda-030d5543e916.png)

That's when idling in the background, rendering nothing at 5fps ☝️

**Comment by axaluss** [comment]
fixed in 3.14.159
