### ISSUE TITLE
Problem using Shift key

### ISSUE THREAD

**Issue by lischetzke** [axaluss/power-mode-intellij-plugin#31]
When I use the Shift key, I can't type any upper letter. Only using caps lock.
This problem appears while using "Scalagen, Java to Scala converter".
I use IntelliJ IDEA 2016.3.4 with pre compiled plugin version 3.14.159265

**Comment by axaluss** [comment]
Does this happen in any other platform you are using?

**Comment by axaluss** [comment]
can't reproduce
