### ISSUE TITLE
Find action list - Toogle is not working

### ISSUE THREAD

**Issue by igorwojda** [axaluss/power-mode-intellij-plugin#32]
1. Open 'Find Action' popup
2. Select power mode using keyboard 
3. Press Enter 

Result: Nothing happened
Expected: Power mode toggle switched (enabled/disabled)

Tested on Android Studio 3.0.1

**Comment by axaluss** [comment]
The 'Toggle Power Mode II   ctrl+alt+shift+O' is visible in the Settings > Power Mode II > ACTIVATE POWER MODE checkbox.
This toggle enables and disables the visualizations. And works on my machine.

There is another toggle in the find action dialogue which disables the plugin completely. That one works on my machine.
