### ISSUE TITLE
Power Mode not working on new files

### ISSUE THREAD

**Issue by okke-formsma** [axaluss/power-mode-intellij-plugin#36]
In PyCharm, PowerMode does not active for newly created files. 

* Open PyCharm
* Create new file in the project
* The new file opens automatically
* No PowerMode 😢 
* Close the file
* Re-open the file
* PowerMode active! 👍 

version info:
PyCharm 2018.2.4 (Professional Edition)
Build #PY-182.4505.26, built on September 19, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by axaluss** [comment]
fixed in [48.84](https://github.com/axaluss/power-mode-intellij-plugin/releases/tag/48.84)
