### ISSUE TITLE
Bad IdeaVim Compatibility

### ISSUE THREAD

**Issue by balugege** [axaluss/power-mode-intellij-plugin#38]
I am using this plugin together with the IdeaVim Plugin.
I turned off "VISUALIZE EVERY CARET MOVEMENT!" in the settings.

Sadly all effects are still displayed when moving the carret in normal mode with h,j,k,l.
Moving the caret with the arrow keys works fine.

Would be nice if this could be improved so that moving the caret in vim normal mode does not trigger effects.

**Comment by axaluss** [comment]
try https://github.com/axaluss/power-mode-intellij-plugin/releases/tag/97.68

**Comment by axaluss** [comment]
There is a new option "HOTKEY HEATUP".  Try disabling it.
