### ISSUE TITLE
Powermode II Shake Effect breaks Jetbrains Autocompletion in 2019.2.x

### ISSUE THREAD

**Issue by Davoleo** [axaluss/power-mode-intellij-plugin#43]
I had my shake effect set on 2 and after updating to 2019.2 autocompletion started to become buggy and started disappearing while writing

Solution: Disable Shake Effect in the settings

_Just putting this out here for other people who experience the same thing_

**Comment by Rollo-Liu** [comment]
I am having this issue too (on the latest version of Rider). Very annoying so I have to disable Power Mode II which makes me so sad.

Any ETA of fixing this?

**Comment by axaluss** [comment]
ATM i'm having trouble to build power mode at all. 
So there won't be updates until i can build it.

**Comment by Davoleo** [comment]
you don't have to disable power mode completely, you can just disable the
shake feature in the settings to have a temp fix @Rollo-Liu
