### ISSUE TITLE
No longer able to see config in Preferences | Appearance & Behavior | Power Mode II after update to new version 98.98

### ISSUE THREAD

**Issue by SashaMoe** [axaluss/power-mode-intellij-plugin#50]
I'm no longer able to see any config in Preferences | Appearance & Behavior | Power Mode II after update to new version 98.98. It only says "Select configuration element in the tree to edit its setting". Did config get moved to other place? I'm on IntelliJ IDEA 2019.1.4

**Comment by SashaMoe** [comment]
NVM, updated to 2019.3 solve the problem

**Comment by axaluss** [comment]
The new intellij internally moved to java 11. I'll take a look to compile
for older intellij with java 8 support.
You can try upgrading to latest version of intellij though. Or you
configure the old intellij version to use a java 11 version provided by you
i.e. by adapting the intellij startup script.
