### ISSUE TITLE
Custom bam images cycles through images in the directory during a "bam"

### ISSUE THREAD

**Issue by akettmann-e24** [axaluss/power-mode-intellij-plugin#52]
Currently when I provide custom "bam" images in a directory, in the course of a single "bam" it does a cycle of all of the images instead of picking one and making it the image for that one "bam" event.

Is that intended or is there a different way I should be supplying the images? Should it be subdirectories? couldn't find any docs showing details on that feature. 

Also it brings a little bit of joy while coding, thanks for the work on this plugin!

**Comment by axaluss** [comment]
the idea is to make an animation possible in a simple way. if you want a single image, put it into a folder all by its own. You can either have a single image, or a cycle through.

**Comment by axaluss** [comment]
There could be an option to pick one per bam event.

**Comment by axaluss** [comment]
fixed in release https://github.com/axaluss/power-mode-intellij-plugin/releases/tag/99.99

**Comment by akettmann-e24** [comment]
Works perfectly, wow thanks for that! Brightens my day, thanks =)
