### ISSUE TITLE
Unable to see options in Android Studio in the settings menu

### ISSUE THREAD

**Issue by manideepl** [axaluss/power-mode-intellij-plugin#53]
![image](https://user-images.githubusercontent.com/52558700/74819581-a0ceee00-5326-11ea-8733-701c2ce142d5.png)

**Comment by btrincao-i9** [comment]
Same problem here ^

**Comment by axaluss** [comment]
@manideepl @btrincao-i9 I need your "about android studio" dialog info.

**Comment by btrincao-i9** [comment]
Android Studio 3.5.1
Build #AI-191.8026.42.35.5900203, built on September 25, 2019
JRE: 1.8.0_202-release-1483-b49-5587405 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.4

I installed the plugin on Preferences > Plugins > Marketplace. 
Power Mode II v99.99

**Comment by halohoop** [comment]
Same problem here on MacOS  here.
------------------------
Android Studio 3.6
Build #AI-192.7142.36.36.6200805, built on February 12, 2020
Runtime version: 1.8.0_212-release-1586-b4-5784211 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.3

**Comment by axaluss** [comment]
somehow my intellij compiles things in a weird way. Plugin source code is java8 compatible except for the UI elements.
I tried to use older IJ versions but those won't build the plugin for some reason.
There is a simple workaround though: switch to boot with java 11 jdk to run android studio.
https://www.jetbrains.com/help/idea/switching-boot-jdk.html
