### ISSUE TITLE
The settings to spark color range cannot be completely saved

### ISSUE THREAD

**Issue by JackieCheung** [axaluss/power-mode-intellij-plugin#54]
When start the IntelliJ next time, it can't automatically apply the spark color range I modified and saved last time. Especially the spark color blue range, I have turned 'blueFrom' to 175 and saved, but start the IntelliJ next time, it's still the old value.
Version: 
IntelliJ IDEA 2019.3.3 (Ultimate Edition)
Power Mode II 99.99

**Comment by JackieCheung** [comment]
Is there a solution now?

**Comment by JackieCheung** [comment]
Why set this range limit? This may be the reason why I set blueFrom to 175 not take effect....😂

![power-mode-intellij-plugin-PowerMode-scala-at-master-·-axaluss-power-mode-intellij-plugin](https://user-images.githubusercontent.com/31252046/104977294-24fb8b00-5a3a-11eb-965e-2fd194165b2c.png)

**Comment by axaluss** [comment]
This is meant to adjust the from to the to and the other way around in the ui. But yeah i think this is mixing up persistence and ui logic so there is a reset happening. I'll fix it in the next release. Feel free to make a PR

**Comment by axaluss** [comment]
@JackieCheung i think this is fixed now
