### ISSUE TITLE
Music is hard to get working

### ISSUE THREAD

**Issue by Stevemoretz** [axaluss/power-mode-intellij-plugin#56]
Music is hard to get working, since it is experminal it is fine but I suggest you to take a look at this package :

https://github.com/izhangzhihao/intellij-rainbow-fart

It doesn't need JavaFX for it in order to run and works pretty smooth and perfect.

I really loved it if the amazing sparkels had sound too but I couldn't get it working.And didn't want actually to use JavaFX to make my environment heavier than it already is.

**Comment by axaluss** [comment]
fixed in [102.201](https://github.com/axaluss/power-mode-intellij-plugin/releases/tag/102.201)
