### ISSUE TITLE
This should also play epic music

### ISSUE THREAD

**Issue by ZeWaren** [axaluss/power-mode-intellij-plugin#6]
This plugin should also make sounds:
- Epic music.
- Lasers / explosions sounds.
- Powerful voices.
- Etc.

What do you think of the idea?

**Comment by axaluss** [comment]
i love the idea!

**Comment by axaluss** [comment]
Which sounds could be played at what event?

**Comment by axaluss** [comment]
in release 2.8.6 epic music can be played

**Comment by EpocDotFr** [comment]
Awesome
