### ISSUE TITLE
Framerate settings is always set to default

### ISSUE THREAD

**Issue by Gazoon007** [axaluss/power-mode-intellij-plugin#64]
When I set framerate value to any number, it's always keep resetting to 30, why is that?
![image](https://user-images.githubusercontent.com/27797762/235339117-11740716-fc07-41d2-9296-8e0e658b3653.png)

**Comment by axaluss** [comment]
should be fixed in [Release 103.301](https://github.com/axaluss/power-mode-intellij-plugin/releases/tag/103.301)

**Comment by declanchiu** [comment]
> should be fixed in [Release 103.301](https://github.com/axaluss/power-mode-intellij-plugin/releases/tag/103.301)应在版本 103.301 中修复

But I installed the 105.501 version of power mode ii on goland and still had this problem.
