### ISSUE TITLE
the plugin is not working / changes to settings are not saved

### ISSUE THREAD

**Issue by axaluss** [axaluss/power-mode-intellij-plugin#68]
Due to some changes in settings, you might need to clear caches to delete the old settings format:

![image](https://github.com/axaluss/power-mode-intellij-plugin/assets/342630/1ff3fc05-7cd1-43de-a453-8bf75e26186a)

**Comment by Gazoon007** [comment]
On Rider 2023.2.3, the plugin is still not working even after invalidating caches.
